// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Context;

namespace Test.Migrations
{
    [DbContext(typeof(CalculationContext))]
    [Migration("20221210211102_MigrationV1")]
    partial class MigrationV1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test.Models.CalculationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("calcDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("field1")
                        .HasColumnType("float");

                    b.Property<double>("field2")
                        .HasColumnType("float");

                    b.Property<int>("operationTypeId")
                        .HasColumnType("int");

                    b.Property<double>("result")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CalculationHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
